language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      compiler: clang

before_install:
  - ./travis/install-deps.sh

script:
  - qmake -r QMAKE_CC=$CC QMAKE_CXX=$CXX
  - make
  - cd ./test
  - ./test -platform offscreen

after_success:
  - cd ..
  - ./travis/publish-docs.sh
