language: cpp
compiler:
  - clang
before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt551
  - sudo apt-get update
  - sudo apt-get install -y qt55base qt55declarative
script:
  - source /opt/qt55/bin/qt55-env.sh
  - qmake -r QMAKE_CC=$CC QMAKE_CXX=$CXX
  - make
  - export LD_LIBRARY_PATH=$PWD/qmlbind
  - cd ./test
  - ./test -platform offscreen
