language: cpp
compiler:
  - clang

before_install:
  # doxygen binary install based on https://github.com/gadomski/fgt/blob/master/scripts/gh-pages.sh
  - export DOXYGEN_VER=doxygen-1.8.11
  - export DOXYGEN_TAR=${DOXYGEN_VER}.linux.bin.tar.gz
  - export DOXYGEN_URL="http://ftp.stack.nl/pub/users/dimitri/${DOXYGEN_TAR}"
  - sudo apt-add-repository -y ppa:beineri/opt-qt551
  - sudo apt-get update
  - sudo apt-get install -y qt55base qt55declarative

script:
  - source /opt/qt55/bin/qt55-env.sh
  - qmake -r QMAKE_CC=$CC QMAKE_CXX=$CXX
  - make
  - cd ./test
  - ./test -platform offscreen

after_success:
  - cd ..
  - sudo pip install ghp-import
  - wget -O - "${DOXYGEN_URL}" | tar xz -C ${TMPDIR-/tmp} ${DOXYGEN_VER}/bin/doxygen
  - export PATH="${TMPDIR-/tmp}/${DOXYGEN_VER}/bin:$PATH"
  - bash .travis-publish-docs.sh
