language: cpp
before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt54
  - sudo apt-get update
  - sudo apt-get install -y qt54base qt54declarative
script:
  - source /opt/qt54/bin/qt54-env.sh
  - qmake -r
  - cd qmlbind
  - make
  - export LD_LIBRARY_PATH=$PWD
  - cd ../test
  - make
  - ./test
